version: '3'

services:
  rclex_docker:
    build: .
    image: rclex/rclex_docker:latest  # foxy-ex1.12.3-otp24.1.5
    volumes:
      - ../rclex:/root/rclex
      - .:/root/rclex_bench/
    working_dir: /root/rclex_bench
    environment:
      - ERL_AFLAGS=-kernel shell_history enabled
    tty: true
